### ISSUE TITLE
feat: 메인페이지 검색바 내 드롭다운 구현

### ISSUE THREAD

**Issue by minhyeokG0** [teamCampro/campro_FE#22]
feat: 메인페이지 검색바 내 드롭다운 구현

- [ ] 장소 dropdown
- [ ]  calendar dropdown
- [ ] 인원선택 dropdown
- [ ] react-datepicker 스타일 수정(pc, tablet 완료, 모바일 90%완료)

**Comment by namminimi** [comment]
모바일쪽 상단 스타일과 버튼쪽 기능 추가해야함
